<?php
/**
 * Implementation of hook_init().
 */
function region_filter_init() {}


function region_filter_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
 /* global $user, $base_url;*/
  switch ($op) {

    case 'view':

             
	     
	     
	     if( arg(0)=='taxonomy' || arg(0)=='category') {
	      $link = 'http://national.thedelimagazine.com/homepage';
          drupal_goto($link, $query = NULL, $fragment = NULL, $http_response_code = 301);
	  }
	     
	     
      if( (arg(1) == 0)){ }
	  
	  else {
	  
        $region = getRegion();
        /*$other = array('boston', 'burlington', 'connecticut', 'portland-me', 'providence');*/
        $national = 'national';
       // $node = node_load(arg(1));
        $count = count($node->taxonomy);//prints number in array
        
        $terms = array();
        foreach($node->taxonomy as $term) {    
          $terms[$term->name] = $term->name; //prints array of individual terms
	  
	 
	
        }
        
	//print 'debug :<pre>'. check_plain(print_r($terms , 1)) . '</pre>';
	

	
	/*case 1 new england*/
       
	
	if( $count < 9 &&  $count > 2 && in_array('newengland', $terms) && $region != 'newengland')
	{
	  $link = 'http://newengland.thedelimagazine.com/' . drupal_get_path_alias("node/$node->nid", $path_language = '');
          drupal_goto($link, $query = NULL, $fragment = NULL, $http_response_code = 301);
	}
	/*END case 1 new england*/
	
 
	       /*  ++++++++case 3 national+++++++++  changed logic, but  we get the same result*/ 
	 //if( in_array('national', $terms) &&  in_array('nashville', $terms)&&  in_array('nyc', $terms) &&  in_array('boston, $terms)&& $region != 'national' )  THIS DOES NOT WORK but logic is accurate because if ever this combination redirect to National
	if($count > 10  && in_array('national', $terms)  && $region != 'national' ) {    //this works              
          $link = 'http://national.thedelimagazine.com/' . drupal_get_path_alias("node/$node->nid", $path_language = '');
          drupal_goto($link, $query = NULL, $fragment = NULL, $http_response_code = 301);     
	}
         /* ++ END case 3 national++*/
	 
	
	 
	
	
      
     
  
        else {
	
	 
	 
	 	
         /*++++++++case 2+++++++++*/
	
		
          if($count == 2 && in_array('national', $terms) && !in_array('washington', $terms) && arg(1) !== '8210' && is_numeric(arg(1))) {  //remove washington washington redirects to cdofthemonth for some reason.
          unset($terms['national']);

          $value = array_shift($terms) ;//returns value of what is left in the array
          if($value == 'los angeles') {
            $value = 'la';
          }      
          if($region == 'los angeles' ) {
            $region = 'la';
          }
          if($region != $value) {
     
              $link = 'http://' . $value . '.thedelimagazine.com/' . drupal_get_path_alias("node/$node->nid", $path_language = '');
              //   print 'debug :<pre>'. check_plain(print_r($region, 1)) . '</pre>';
            drupal_goto($link, $query = NULL, $fragment = NULL, $http_response_code = 301);
          }         
        }

        /* ++ END case 2++*/
       
	 
	 
	 
	 
         }
     }
      break;
  }
}

/*
 If has washington tag, redirects to cd of the month
 
 if is the frontpage also redirects to cd of the month and ads in washington array in second/duplicate array
 

*/











