<?php
/**
 * Implementation of hook_init().
 */
function region_filter_init() {

}


function region_filter_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  global $user, $base_url;
  switch ($op) {

    case 'view':

     //  if($user->uid == 1/* && arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)*/) {
        $region = getRegion();
        $other = array('boston', 'burlington', 'connecticut', 'portland-me', 'providence');
        $national = 'national';
       // $node = node_load(arg(1));
        $count = count($node->taxonomy);
        
        $terms = array();
        foreach($node->taxonomy as $term) {    
          $terms[$term->name] = $term->name;
        }
        
      
        if( (arg(1) == 0)){  }
        
      else {
       
       
       if($count > 2  && in_array('national', $terms) && in_array('los angeles', $terms)  && $region != 'national') {                  
          $link = 'http://national.thedelimagazine.com/' . drupal_get_path_alias("node/$node->nid", $path_language = '');;
          drupal_goto($link, $query = NULL, $fragment = NULL, $http_response_code = 301);     
        
        }
     /*
       //$value needs to = $region name : la not los angeles
        elseif($count == 2 && in_array('national', $terms)) {
          unset($terms['national']);
          $value = array_shift($terms) ;
          if($region != $value) {
            $link = 'http://' . $value . '.thedelimagazine.com/' . drupal_get_path_alias("node/$node->nid", $path_language = '');
            drupal_goto($link, $query = NULL, $fragment = NULL, $http_response_code = 301);
          }         
        }
      */
        
        
        
        /*  ++++++++case 3+++++++++ */ 
       elseif( in_array($other, $terms) && $region != 'newengland')
	{
	     $link = 'http://newengland.thedelimagazine.com/' . drupal_get_path_alias("node/$node->nid", $path_language = '');
               drupal_goto($link, $query = NULL, $fragment = NULL, $http_response_code = 301);
	 
	}
       /* +++++++end case3+++++++++*/
        
      }
      break;
  }
}
